---
kind: pipeline
name: user-python-2.7-alpine
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-alpine-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/python:2.7-alpine

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-alpine-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/python:2.7-alpine

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-alpine-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/python:2.7-alpine

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-python:2.7-alpine
    template: phasecorex/user-python:2.7-alpine-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-python-2.7-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/python:2.7-slim

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-slim-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/python:2.7-slim

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-slim-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/python:2.7-slim

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-python:2.7-slim
    template: phasecorex/user-python:2.7-slim-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-python-2.7
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/python:2.7

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/python:2.7

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 2.7-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/python:2.7

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-python:2.7
    template: phasecorex/user-python:2.7-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-python-3.7-alpine
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-alpine-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/python:3.7-alpine

- name: docker-build-arm32v6
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-alpine-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v6/python:3.7-alpine

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-alpine-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.alpine.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/python:3.7-alpine

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-python:3.7-alpine
    template: phasecorex/user-python:3.7-alpine-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-python-3.7-slim
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-slim-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/python:3.7-slim

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-slim-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/python:3.7-slim

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-slim-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/python:3.7-slim

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-python:3.7-slim
    template: phasecorex/user-python:3.7-slim-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-python-3.7
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/python:3.7

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/python:3.7

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: 3.7-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/python:3.7

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-python:3.7
    template: phasecorex/user-python:3.7-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

---
kind: pipeline
name: user-python-latest
trigger:
  branch:
  - master
  event:
  - push

steps:
- name: submodules
  image: docker:git
  commands:
  - git submodule update --init --recursive
  - ls -la docker-user-image

- name: docker-build-amd64
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: latest-amd64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian
    build_args:
      - QEMU_ARCH=x86_64
      - ARCH_IMG=amd64/python:latest

- name: docker-build-arm32v7
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: latest-arm
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=arm
      - ARCH_IMG=arm32v7/python:latest

- name: docker-build-arm64v8
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: phasecorex/user-python
    tags: latest-arm64
    context: docker-user-image
    dockerfile: docker-user-image/Dockerfile.debian.qemu
    build_args:
      - QEMU_ARCH=aarch64
      - ARCH_IMG=arm64v8/python:latest

- name: docker-push-manifest
  image: plugins/manifest:1
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: phasecorex/user-python:latest
    template: phasecorex/user-python:latest-ARCH
    platforms:
      - linux/amd64
      - linux/arm
      - linux/arm64

